name: CatLate

options:
  minimumXcodeGenVersion: 2.45.0

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.catlyte
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    MARKETING_VERSION: 0.0.1
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

targets:
  CatLate:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: CatLate
        excludes:
          - Info.plist
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: CatLate
        INFOPLIST_FILE: CatLate/Info.plist
  CatLateTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: CatLateTests
    dependencies:
      - target: CatLate
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.catlyte.tests

schemes:
  CatLate:
    build:
      targets:
        CatLate: all
        CatLateTests: [test]
    test:
      gatherCoverageData: true
      targets:
        - name: CatLateTests
    run:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
    analyze:
      config: Debug
